name: front
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.2.4
  image_picker: ^1.1.2
  flutter_svg: ^2.1.0
  http: ^1.3.0 # Atau versi terbaru
  async: ^2.11.0 # Atau versi terbaru
  get: ^4.7.2
  file_picker: ^10.1.2
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  injectable: ^2.5.0
  bloc: ^9.0.0
  shimmer: ^3.0.0
  dotenv: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icons/
