name: front
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

fonts:
  - family: Noto
    fonts:
      - asset: assets/fonts/NotoSans-Regular.ttf


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.2.4
  image_picker: ^1.1.2
  flutter_svg: ^2.1.0
  http: ^1.3.0 # Atau versi terbaru
  async: ^2.11.0 # Atau versi terbaru
  get: ^4.7.2
<<<<<<< Updated upstream
=======
  file_picker: ^10.1.2
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  injectable: ^2.5.0
  bloc: ^9.0.0
  shimmer: ^3.0.0
  dotenv: ^4.2.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_location_marker: ^10.1.0
  geocoding: ^3.0.0
  liquid_pull_to_refresh: ^3.0.0
  mime: ^1.0.4
  path: ^1.8.3
  http_parser: ^4.0.2
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
