import 'package:flutter/material.dart';
import 'package:front/features/room/data/models/room_model.dart';
import 'package:front/features/room/data/repositories/room_repository.dart';

class AddRoomScreen extends StatefulWidget {
  static const routeName = '/add_room';
  final int propertyId;

  const AddRoomScreen({Key? key, required this.propertyId}) : super(key: key);

  @override
  _AddRoomScreenState createState() => _AddRoomScreenState();
}

class _AddRoomScreenState extends State<AddRoomScreen> {
  final _formKey = GlobalKey<FormState>();
  final _roomTypeController = TextEditingController();
  final _roomNumberController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _priceController = TextEditingController();
  final _sizeController = TextEditingController();
  final _capacityController = TextEditingController();
  final _isAvailableController = TextEditingController(text: 'true'); // Default value
  final RoomRepository _roomRepository = RoomRepository();

  Future<void> _addRoom() async {
    if (_formKey.currentState!.validate()) {
      final newRoom = Room(
        id: 0, // Will be generated by the backend
        propertyId: widget.propertyId,
        roomType: _roomTypeController.text,
        roomNumber: _roomNumberController.text,
        description: _descriptionController.text,
        price: double.parse(_priceController.text),
        size: _sizeController.text.isNotEmpty ? _sizeController.text : null,
        capacity: int.tryParse(_capacityController.text),
        isAvailable: _isAvailableController.text.toLowerCase() == 'true',
      );

      Room? addedRoom = await _roomRepository.addRoom(newRoom);
      if (addedRoom != null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Kamar berhasil ditambahkan')),
        );
        Navigator.pop(context); // Kembali ke daftar kamar
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Gagal menambahkan kamar')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Tambah Kamar Baru'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              TextFormField(
                controller: _roomTypeController,
                decoration: const InputDecoration(labelText: 'Tipe Kamar'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Tipe kamar tidak boleh kosong';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _roomNumberController,
                decoration: const InputDecoration(labelText: 'Nomor Kamar'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Nomor kamar tidak boleh kosong';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(labelText: 'Deskripsi (Opsional)'),
              ),
              TextFormField(
                controller: _priceController,
                decoration: const InputDecoration(labelText: 'Harga'),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Harga tidak boleh kosong';
                  }
                  if (double.tryParse(value) == null || double.parse(value) < 0) {
                    return 'Masukkan harga yang valid';
                  }
                  return null;
                },
              ),
              TextFormField(
                controller: _sizeController,
                decoration: const InputDecoration(labelText: 'Ukuran (Opsional)'),
              ),
              TextFormField(
                controller: _capacityController,
                decoration: const InputDecoration(labelText: 'Kapasitas (Opsional)'),
                keyboardType: TextInputType.number,
              ),
              TextFormField(
                controller: _isAvailableController,
                decoration: const InputDecoration(labelText: 'Ketersediaan (true/false)'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Ketersediaan tidak boleh kosong';
                  }
                  if (value.toLowerCase() != 'true' && value.toLowerCase() != 'false') {
                    return 'Masukkan "true" atau "false"';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _addRoom,
                child: const Text('Simpan Kamar'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}